import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import type { ContentRow } from "@/data/collections";
import type { BlogPost, Country, SuccessStory, TeamMember } from "@/data/content";
import type { CopyRow } from "@/data/page-copy";
import type { SiteSettings } from "@/data/site";

/**
 * A contact form submission. Anyone may insert one; only a signed-in staff
 * member can read them back, so the shape below is the whole record and the
 * public form only ever fills the first six fields.
 */
export type Enquiry = {
  id: string;
  name: string;
  phone: string;
  email: string;
  destination: string;
  test: string;
  message: string;
  status: EnquiryStatus;
  notes: string;
  created_at: string;
  updated_at: string;
};

export const enquiryStatuses = ["new", "contacted", "closed"] as const;

export type EnquiryStatus = (typeof enquiryStatuses)[number];

/** What the public form is allowed to send. status and notes stay at defaults. */
export type EnquiryInput = Pick<
  Enquiry,
  "name" | "phone" | "email" | "destination" | "test" | "message"
>;

/**
 * Supabase rows for the admin-managed tables. `id` is a uuid generated by
 * Postgres, so inserts omit it.
 *
 * Shaped to match what supabase-js expects from a generated `Database` type,
 * the empty Views/Functions/Enums/CompositeTypes members are required for the
 * client's query builder generics to resolve.
 */
type TableShape<Row extends { id: string }> = {
  Row: Row & { created_at: string; updated_at: string };
  Insert: Omit<Row, "id">;
  Update: Partial<Omit<Row, "id">>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      blog_posts: TableShape<BlogPost>;
      success_stories: TableShape<SuccessStory>;
      team_members: TableShape<TeamMember>;
      countries: TableShape<Country>;
      /** Every editable list on the site, discriminated by `collection`. */
      site_content: TableShape<ContentRow>;
      /**
       * Heading overrides for the marketing pages, keyed by `(page, section)`.
       * The save path upserts on that pair, which is why it is a unique index in
       * the schema rather than just a lookup one.
       */
      page_sections: TableShape<CopyRow>;
      site_settings: {
        Row: SiteSettings & { created_at: string; updated_at: string };
        // `id` is included rather than omitted, unlike the uuid tables: the save
        // path upserts on it to create-or-update the single row in one call.
        Insert: SiteSettings;
        Update: Partial<SiteSettings>;
        Relationships: [];
      };
      enquiries: {
        Row: Enquiry;
        // Timestamps and the staff-only columns are all defaulted in Postgres.
        Insert: EnquiryInput;
        Update: Partial<Pick<Enquiry, "status" | "notes">>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

/**
 * True once both env vars are present. Every read path falls back to the seed
 * content in `src/data/content.ts` when this is false, so the public site works
 * before Supabase is wired up.
 */
export const isSupabaseConfigured = Boolean(url && anonKey);

/**
 * Deep link to this project's SQL editor, or null when the URL is not a hosted
 * Supabase project (self-hosted, or a local `supabase start`).
 *
 * Derived from the configured URL rather than hardcoded, so the setup card in
 * /admin points at the reader's own project. The ref is the first label of
 * `<ref>.supabase.co` and is not a secret — it is the API host every visitor's
 * browser already connects to.
 */
export const sqlEditorUrl: string | null = (() => {
  const ref = url?.match(/^https:\/\/([a-z0-9]+)\.supabase\.co\/?$/i)?.[1];
  return ref ? `https://supabase.com/dashboard/project/${ref}/sql/new` : null;
})();

let client: SupabaseClient<Database> | null = null;

/** Returns the shared client, or null when Supabase is not configured. */
export function getSupabase(): SupabaseClient<Database> | null {
  if (!isSupabaseConfigured) return null;
  if (!client) {
    client = createClient<Database>(url!, anonKey!, {
      auth: {
        // Admin sessions persist in localStorage; this only runs in the browser.
        persistSession: typeof window !== "undefined",
        autoRefreshToken: typeof window !== "undefined",
        detectSessionInUrl: false,
      },
    });
  }
  return client;
}
