import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import type { BlogPost, Country, SuccessStory, TeamMember } from "@/data/content";

/**
 * A contact form submission. Anyone may insert one; only a signed-in staff
 * member can read them back, so the shape below is the whole record and the
 * public form only ever fills the first six fields.
 */
export type Enquiry = {
  id: string;
  name: string;
  phone: string;
  email: string;
  destination: string;
  test: string;
  message: string;
  status: EnquiryStatus;
  notes: string;
  created_at: string;
  updated_at: string;
};

export const enquiryStatuses = ["new", "contacted", "closed"] as const;

export type EnquiryStatus = (typeof enquiryStatuses)[number];

/** What the public form is allowed to send. status and notes stay at defaults. */
export type EnquiryInput = Pick<
  Enquiry,
  "name" | "phone" | "email" | "destination" | "test" | "message"
>;

/**
 * Supabase rows for the admin-managed tables. `id` is a uuid generated by
 * Postgres, so inserts omit it.
 *
 * Shaped to match what supabase-js expects from a generated `Database` type,
 * the empty Views/Functions/Enums/CompositeTypes members are required for the
 * client's query builder generics to resolve.
 */
type TableShape<Row extends { id: string }> = {
  Row: Row & { created_at: string; updated_at: string };
  Insert: Omit<Row, "id">;
  Update: Partial<Omit<Row, "id">>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      blog_posts: TableShape<BlogPost>;
      success_stories: TableShape<SuccessStory>;
      team_members: TableShape<TeamMember>;
      countries: TableShape<Country>;
      enquiries: {
        Row: Enquiry;
        // Timestamps and the staff-only columns are all defaulted in Postgres.
        Insert: EnquiryInput;
        Update: Partial<Pick<Enquiry, "status" | "notes">>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

/**
 * True once both env vars are present. Every read path falls back to the seed
 * content in `src/data/content.ts` when this is false, so the public site works
 * before Supabase is wired up.
 */
export const isSupabaseConfigured = Boolean(url && anonKey);

let client: SupabaseClient<Database> | null = null;

/** Returns the shared client, or null when Supabase is not configured. */
export function getSupabase(): SupabaseClient<Database> | null {
  if (!isSupabaseConfigured) return null;
  if (!client) {
    client = createClient<Database>(url!, anonKey!, {
      auth: {
        // Admin sessions persist in localStorage; this only runs in the browser.
        persistSession: typeof window !== "undefined",
        autoRefreshToken: typeof window !== "undefined",
        detectSessionInUrl: false,
      },
    });
  }
  return client;
}
