/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestPreparationRouteImport } from './routes/test-preparation'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as SuccessStoriesIndexRouteImport } from './routes/success-stories/index'
import { Route as SuccessStoriesSlugRouteImport } from './routes/success-stories/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPreparationRoute = TestPreparationRouteImport.update({
  id: '/test-preparation',
  path: '/test-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesIndexRoute = SuccessStoriesIndexRouteImport.update({
  id: '/success-stories/',
  path: '/success-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesSlugRoute = SuccessStoriesSlugRouteImport.update({
  id: '/success-stories/$slug',
  path: '/success-stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-preparation': typeof TestPreparationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-preparation': typeof TestPreparationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/success-stories': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-preparation': typeof TestPreparationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/success-stories/$slug': typeof SuccessStoriesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/countries'
    | '/sitemap.xml'
    | '/test-preparation'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/countries'
    | '/sitemap.xml'
    | '/test-preparation'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/countries'
    | '/sitemap.xml'
    | '/test-preparation'
    | '/blog/$slug'
    | '/success-stories/$slug'
    | '/blog/'
    | '/success-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestPreparationRoute: typeof TestPreparationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SuccessStoriesSlugRoute: typeof SuccessStoriesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SuccessStoriesIndexRoute: typeof SuccessStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-preparation': {
      id: '/test-preparation'
      path: '/test-preparation'
      fullPath: '/test-preparation'
      preLoaderRoute: typeof TestPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/': {
      id: '/success-stories/'
      path: '/success-stories'
      fullPath: '/success-stories/'
      preLoaderRoute: typeof SuccessStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/$slug': {
      id: '/success-stories/$slug'
      path: '/success-stories/$slug'
      fullPath: '/success-stories/$slug'
      preLoaderRoute: typeof SuccessStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestPreparationRoute: TestPreparationRoute,
  BlogSlugRoute: BlogSlugRoute,
  SuccessStoriesSlugRoute: SuccessStoriesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  SuccessStoriesIndexRoute: SuccessStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
